#!/usr/bin/env csh


mkdir -p build
cd build

pandoc --toc --toc-depth=2 --chapters --natbib --template=../book_template.tex -o "Measure Of Faith.tex" "../Measure Of Faith.md"

pdflatex "Measure Of Faith.tex"
#bibtex "Measure Of Faith"
pdflatex "Measure Of Faith.tex"

open "Measure of Faith.pdf"
